version: "3.3"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    networks:
      - test_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mels9ka_bd
      MYSQL_USER: mels9ka
      MYSQL_PASSWORD: password
    ports:
      - "9907:3306"
    volumes:
      - test_database:/var/lib/mysql

  php-apache-environment:
    container_name: php-apache
    networks:
      - test_network
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

volumes:
  test_database:

networks:
  test_network: