version: "3.3"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mels9ka_bd
      MYSQL_USER: mels9ka
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"